
Simon : main.o specialLL.o linkedlist.o
        gcc -o -lm Simon  main.o specialLL.o linkedlist.o

main.o: main.c
        gcc -c main.c

specialLL.o: specialLL.c specialLL.h
        gcc -c specialLL.c

linkedlist.o: linkedlist.c linkedlist.h
        gcc -c linkedlist.c